commit	modified:   .github/workflows/run_tests.yml

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -26,9 +26,9 @@ jobs:
         python -m pytest -r CD/
     - name: Check test results
       run: |
-      if [ $? -eq 0 ]; then
-        echo "Tests passed, proceeding with deployment"
-      else
-        echo "Tests failed, skipping deployment"
-        exit 1
-      fi
+        if [ $? -eq 0 ]; then
+          echo "Tests passed, proceeding with deployment"
+        else
+          echo "Tests failed, skipping deployment"
+          exit 1
+        fi
